In [ ]:
#tensorflow ReLUs
#Don't run this cell

hidden_layer = tf.add(tf.matmul(features, hidden_weights), hidden_biases)
hidden_layer = tf.nn.relu(hidden_layer)
output = tf.add(tf.matmul(hidden_layer, output_weights), output_biases)

In [10]:
import tensorflow as tf

output = None
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]

out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])
print(features.shape)

# TODO: Create Model
hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)
output = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])

# TODO: Print session results
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(output))

(3, 4)
[[  5.11000013   8.44000053]
 [  0.           0.        ]
 [ 24.01000214  38.23999786]]


In [3]:
#tensorflow MNIST
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets(".", one_hot=True, reshape=False)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting ./train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting ./train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting ./t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting ./t10k-labels-idx1-ubyte.gz


In [5]:
learning_rate = 0.001
training_epochs = 20
batch_size = 128
display_step = 1

n_input = 784
n_classes = 10

In [17]:
n_hidden_layer = 256

weights = {
    'hidden_layer':tf.Variable(tf.random_normal([n_input, n_hidden_layer])),
    'out':tf.Variable(tf.random_normal([n_hidden_layer, n_classes]))
}

biases = {
    'hidden_layer': tf.Variable(tf.random_normal([n_hidden_layer])),
    'out':tf.Variable(tf.random_normal([n_classes]))
}

x = tf.placeholder("float", [None, 28, 28, 1])
y = tf.placeholder("float", [None, n_classes])
x_flat = tf.reshape(x, [-1, n_input])

#Hidden layer with RELU activation
layer_1 = tf.add(tf.matmul(x_flat, weights['hidden_layer']), biases['hidden_layer'])
layer_1 = tf.nn.relu(layer_1)
logits = tf.add(tf.matmul(layer_1, weights['out']), biases['out'])

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    for epoch in range(training_epochs):
        total_batch = int(mnist.train.num_examples/batch_size)
        for i in range(total_batch):
            batch_x, batch_y = mnist.train.next_batch(batch_size)
            sess.run(optimizer, feed_dict={x: batch_x, y: batch_y})

KeyboardInterrupt: 

In [30]:
save_file = './model.ckpt'

weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("weights:")
    print(sess.run(weights))
    print("bias:")
    print(sess.run(bias))
    
    saver.save(sess, save_file)

with tf.Session() as sess2:
    # Load the weights and bias
    saver.restore(sess2, save_file)

    # Show the values of weights and bias
    print('Weight:')
    print(sess2.run(weights))
    print('Bias:')
    print(sess2.run(bias))

weights:
[[-0.09206281 -0.47779301 -0.20210941]
 [-0.40987709  1.18548429 -1.37781346]]
bias:
[ 0.85661757 -1.15626192 -1.03889978]
INFO:tensorflow:Restoring parameters from ./model.ckpt
Weight:
[[-0.09206281 -0.47779301 -0.20210941]
 [-0.40987709  1.18548429 -1.37781346]]
Bias:
[ 0.85661757 -1.15626192 -1.03889978]


In [39]:
tf.reset_default_graph()

from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

learning_rate = 0.001
n_input = 784
n_classes = 10

mnist = input_data.read_data_sets('.', one_hot=True)

features = tf.placeholder(tf.float32, [None, n_input])
labels= tf.placeholder(tf.float32, [None, n_classes])

weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

logits = tf.add(tf.matmul(features, weights), bias)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

Extracting ./train-images-idx3-ubyte.gz
Extracting ./train-labels-idx1-ubyte.gz
Extracting ./t10k-images-idx3-ubyte.gz
Extracting ./t10k-labels-idx1-ubyte.gz


In [40]:
import math 

save_file = './train_model.ckpt'
batch_size = 128
n_epochs = 100

saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(n_epochs):
        total_batch = math.ceil(mnist.train.num_examples / batch_size)
        
        for i in range(total_batch):
            batch_features, batch_labels = mnist.train.next_batch(batch_size)
            sess.run(optimizer, feed_dict={features:batch_features, labels:batch_labels})
            
        if epoch % 10 == 0:
            valid_accuracy = sess.run(accuracy, feed_dict={
                    features:mnist.validation.images, 
                    labels: mnist.validation.labels})
            print('Epoch {:<3} - validation accuracy:{}'.format(epoch, valid_accuracy))
            
    saver.save(sess, save_file)
    print('trained model saved.')

Epoch 0   - validation accuracy:0.13019999861717224
Epoch 10  - validation accuracy:0.25060001015663147
Epoch 20  - validation accuracy:0.3846000134944916
Epoch 30  - validation accuracy:0.48840001225471497
Epoch 40  - validation accuracy:0.5583999752998352
Epoch 50  - validation accuracy:0.6065999865531921
Epoch 60  - validation accuracy:0.6474000215530396
Epoch 70  - validation accuracy:0.6732000112533569
Epoch 80  - validation accuracy:0.6962000131607056
Epoch 90  - validation accuracy:0.7110000252723694
trained model saved.


In [44]:
with tf.Session() as sess:
    tf.train.Saver().restore(sess,save_file)
    
    test_accuracy = sess.run(accuracy, feed_dict={features:mnist.test.images, labels:mnist.test.labels})
    print('Test accuracy: {}'.format(test_accuracy))

INFO:tensorflow:Restoring parameters from ./train_model.ckpt
Test accuracy: 0.7265999913215637
